Add screenshot action
fire-square/autodonate pull request #116
Opened 2022-04-30 16:30 UTC by cofob

2022-04-30 16:55 UTC, cofob commented
[Example](https://github.com/pachimy/autodonate/commit/f7bc6fc1f2da4abbfbffc4d584a6aafb5c1abc3a#commitcomment-72568878)

2022-04-30 17:00 UTC, PerchunPak requested changes

2022-04-30 17:00 UTC, PerchunPak commented on .github/workflows/screenshot.yml
> +        poetry run python manage.py runserver &
Что за `&` и оно же заморозит CI.

2022-04-30 17:00 UTC, PerchunPak commented on .github/workflows/screenshot.yml
> +        poetry run pip install webdriver-manager selenium
Не нужно так. Добавь в `pyproject.toml` с флагом `optional`.

2022-04-30 17:00 UTC, PerchunPak commented on .github/workflows/screenshot.yml
> +        wget https://gist.githubusercontent.com/cofob/648cb6fb18cb092523e86379c17aeba7/raw/56d17c2a6a5c136c1f0c9aa090c07371e4687117/screenshot.py -q
А это еще что? В репозиторий нужно все скрипты.

2022-04-30 17:00 UTC, PerchunPak commented on .github/workflows/screenshot.yml
> +    - name: Upload image to temp.sh
Чем артефакты гитхаба плохи?

2022-04-30 17:01 UTC, cofob commented on .github/workflows/screenshot.yml
> +        poetry run python manage.py runserver &
`&` - спецсимвол `bash`, он не ждёт завершения программы и отправляет её в фон, она там находиться пока жива сессия.

2022-04-30 17:01 UTC, cofob commented on .github/workflows/screenshot.yml
> +        poetry run pip install webdriver-manager selenium
Нет нужды, пусть тут лучше будет. Оно нужно только в 1 месте и только для CI.

2022-04-30 17:02 UTC, cofob commented on .github/workflows/screenshot.yml
> +        wget https://gist.githubusercontent.com/cofob/648cb6fb18cb092523e86379c17aeba7/raw/56d17c2a6a5c136c1f0c9aa090c07371e4687117/screenshot.py -q
Я не хотел засорять репо мусорными скриптами для CI.

2022-04-30 17:02 UTC, cofob commented on .github/workflows/screenshot.yml
> +    - name: Upload image to temp.sh
Так они ниже используются. Проблема в том, что артифакт гитхаба это zip, который нельзя прикрепить ссылкой к комментарию. Его нужно скачать, распаковать и открыть файл.

2022-04-30 17:04 UTC, PerchunPak commented on .github/workflows/screenshot.yml
> +        poetry run pip install webdriver-manager selenium
Сам смысл `pyproject.toml` это хранить там все зависимости и легко ими управлять. Добавь.

2022-04-30 17:05 UTC, PerchunPak commented on .github/workflows/screenshot.yml
> +        wget https://gist.githubusercontent.com/cofob/648cb6fb18cb092523e86379c17aeba7/raw/56d17c2a6a5c136c1f0c9aa090c07371e4687117/screenshot.py -q
Просто добавь в .github папку.

2022-04-30 17:05 UTC, PerchunPak commented on .github/workflows/screenshot.yml
> +    - name: Upload image to temp.sh
Прикрепи локальный файл.

2022-04-30 17:05 UTC, cofob commented on .github/workflows/screenshot.yml
> +        poetry run pip install webdriver-manager selenium
Я не знаю как, можешь это сделать ты?

2022-04-30 17:07 UTC, cofob commented on .github/workflows/screenshot.yml
> +        wget https://gist.githubusercontent.com/cofob/648cb6fb18cb092523e86379c17aeba7/raw/56d17c2a6a5c136c1f0c9aa090c07371e4687117/screenshot.py -q
6faa8cb

2022-04-30 17:08 UTC, cofob commented on .github/workflows/screenshot.yml
> +    - name: Upload image to temp.sh
Легко сказать. Я не смог нагуглить как это сделать, поэтому использую сторонний сервис.

2022-04-30 18:30 UTC, PerchunPak requested changes

2022-04-30 18:30 UTC, PerchunPak commented on setup.cfg
> +exclude = venv|autodonate/migrations|.github
Это не фикс, а наглое игнорирование проблемы.

2022-04-30 18:30 UTC, PerchunPak commented on .github/workflows/screenshot.yml
> +        poetry run pip install webdriver-manager selenium
`poetry add webdriver-manager selenium --optional --dev --extras screenshot-script`

2022-04-30 18:30 UTC, PerchunPak commented on .github/scripts/screenshot.py
> +driver.close()
```py
def main() -> None:
    # your code

if __name__ == "__main__":
    main()
```

2022-04-30 18:48 UTC, cofob commented on .github/workflows/screenshot.yml
> +        poetry run pip install webdriver-manager selenium
Сделай, пожалуйста. Нет доступа к пк

2022-05-01 02:05 UTC, cofob commented on setup.cfg
> +exclude = venv|autodonate/migrations|.github
Какая проблема?! КОД РАБОТАЕТ. Перестань пихать доки и mypy куда не надо.

2022-05-01 02:06 UTC, cofob commented on .github/scripts/screenshot.py
> +driver.close()
Нет. Тут это не нужно.

2022-05-01 02:06 UTC, cofob commented
Я бы понял если ты такие комментарии оставлял на прод-код, но здесь то нахера эти гайдлайны?

2022-05-01 09:13 UTC, PerchunPak approved these changes

2022-05-01 10:12 UTC, cofob commented
ToDo:
 - [ ] Грузить картинки на bin.frsqr.xyz
 - [ ] Делать diff между версиями скринов

2022-05-01 10:46 UTC, merged