ZeroConfig концепция
fire-square/autodonate pull request #77
Opened 2022-04-22 19:01 UTC by PerchunPak

Все настройки будут в базе данных.

# Важный check-list

- [x] Я написал подробное описание моих изменений.
- [x] Я написал подробную причину моих изменений.
- [x] Я точно прочитал и использовал все пункты [этого списка](https://github.com/fire-square/autodonate/blob/master/CONTRIBUTING.md#перед-началом-работы).
- [x] Я записал изменение в `CHANGELOG.md` и добавил номер PR туда.
- [x] Изменения успешно проходят все этапы `make test`.

2022-04-22 19:09 UTC, PerchunPak commented
Так как Django DB не поддерживает lazy-init, нужно писать документацию к моделям самостоятельно.

Короче пора изменить концепцию и стать менее ленивыми.

2022-04-23 03:14 UTC, cofob requested changes
В целом нормально, но:
1. Не вижу где настраивается логгер;
2. У `Config` модели нет методов для получения по ключу и метода обновления;
3. Не понимаю зачем нужен `ConfigParams`;
4. Зачем нужны логгеры в моделях?
5. Миграции сейчас лучше удалить, сделать их потом прямо в `main` ветке.

2022-04-23 03:14 UTC, cofob commented on autodonate/admin.py
> +@admin.register(Config)
Это можно делать в 1 строку. `admin.register(Config)`

2022-04-23 03:14 UTC, cofob commented on autodonate/config.py
> +    project_name: Config = field(default=Config.objects.get("project_name"))
Это зачем?

2022-04-23 03:14 UTC, cofob commented on autodonate/config.py
> +    log.debug("ConfigParams", project_name=project_name)
Логгер настроен?

2022-04-23 03:14 UTC, cofob commented on autodonate/migrations/0001_initial.py
> +    ]
Просил же миграцию пока не делать

2022-04-23 03:14 UTC, cofob commented on autodonate/models.py
> +    log.debug("models.Config", key=key, value=value)
Зачем здесь логгер?

2022-04-23 03:14 UTC, cofob commented on autodonate/models.py
> +    value: str = models.CharField(max_length=255, null=True)
Где `type` поле? Где `classmethod`'ы для простого получения значений по ключу? Почему `value` не `TextField`?

2022-04-23 03:14 UTC, cofob commented on autodonate/models.py
> +    value: str = models.CharField(max_length=255, null=True)
Вообще `value` можно сделать байтами и тупо через `ubjson` это десериализовать. Тогда поле `type` не нужно.

2022-04-23 03:15 UTC, cofob commented
> Так как Django DB не поддерживает lazy-init, нужно писать документацию к моделям самостоятельно.
> 
> Короче пора изменить концепцию и стать менее ленивыми.

А flake8 не будет на это жаловаться?

2022-04-23 07:36 UTC, PerchunPak commented on autodonate/config.py
> +    project_name: Config = field(default=Config.objects.get("project_name"))
Это класс с дефолтными строками (row) для конфига. Просто класс геттер, сами строки добавляются в миграциях.

2022-04-23 07:38 UTC, PerchunPak commented
> > Так как Django DB не поддерживает lazy-init, нужно писать документацию к моделям самостоятельно.
> > Короче пора изменить концепцию и стать менее ленивыми.
> 
> А flake8 не будет на это жаловаться?

Скорее всего будет. Ну прийдется дублировать минимальную документацию в код.

2022-04-23 07:39 UTC, PerchunPak commented on autodonate/config.py
> +    log.debug("ConfigParams", project_name=project_name)
Логгер не нужно настраивать....

2022-04-23 07:40 UTC, PerchunPak commented on autodonate/migrations/0001_initial.py
> +    ]
Не помню чтобы ты просил, но окей, удалю.

2022-04-23 07:42 UTC, PerchunPak commented on autodonate/models.py
> +    value: str = models.CharField(max_length=255, null=True)
`type` поля нет потому что все будет в string'ах. Classmethod'ов тоже нет потому что это можель джанги, я думал это ок получать значения по интерфейсу джанги. `value` исправлю.

2022-04-23 07:44 UTC, PerchunPak commented on autodonate/admin.py
> +@admin.register(Config)
А как тогда настроить пермишины по удалению и добавлению записей вручную?

2022-04-23 07:49 UTC, PerchunPak commented on autodonate/models.py
> +    log.debug("models.Config", key=key, value=value)
Исправил в 37bf79dd36322b94ebe7d6bfc779ac50dc33be84.

2022-04-23 07:49 UTC, PerchunPak commented on autodonate/migrations/0001_initial.py
> +    ]
Удалил в 04b43fefd3e891db76f9d33256aac078c7204672.

2022-04-23 09:51 UTC, cofob commented on autodonate/admin.py
> +@admin.register(Config)
Зачем тебе настройка прав?

2022-04-23 09:51 UTC, cofob commented on autodonate/config.py
> +    project_name: Config = field(default=Config.objects.get("project_name"))
Это не удобно. Лучше просто сделать для `Config` классметоды.

2022-04-23 09:53 UTC, cofob commented on autodonate/models.py
> +    value: str = models.CharField(max_length=255, null=True)
Над неудобным интерфейсом джанги можно писать так же своё.

2022-04-23 09:54 UTC, cofob commented
> > > Так как Django DB не поддерживает lazy-init, нужно писать документацию к моделям самостоятельно.
> > > Короче пора изменить концепцию и стать менее ленивыми.
> > 
> > 
> > А flake8 не будет на это жаловаться?
> 
> Скорее всего будет. Ну прийдется дублировать минимальную документацию в код.

А можно просто flake8 удалить :) Он столько проблем создаёт.

2022-04-24 17:46 UTC, PerchunPak commented
> А можно просто flake8 удалить :) Он столько проблем создаёт.

flake8 мешает только тебе. И проблем совсем не много, все что он просит, это докстринги.

2022-04-24 17:47 UTC, PerchunPak commented on autodonate/admin.py
> +@admin.register(Config)
Чтобы пользователь ничего не сломал.

2022-04-24 17:48 UTC, PerchunPak commented on autodonate/config.py
> +    project_name: Config = field(default=Config.objects.get("project_name"))
Тоесть тупо геттеры? Мы же вроде бы договаривались хранить конфигурацию в датаклассе.

2022-04-25 11:27 UTC, cofob commented
![](https://github.trello.services/images/mini-trello-icon.png) [ZeroConfig](https://trello.com/c/n03ZupvJ/1-zeroconfig)

2022-04-25 11:53 UTC, cofob commented on autodonate/admin.py
> +@admin.register(Config)
Если пользователь админ, то ломать ему можно.

2022-04-25 11:54 UTC, cofob commented on autodonate/config.py
> +    project_name: Config = field(default=Config.objects.get("project_name"))
Да, но я говорил про `aiohttp`, а в джанге принято хранить всё в куче.

2022-04-25 12:40 UTC, cofob approved these changes

2022-04-25 16:02 UTC, PerchunPak commented on autodonate/admin.py
> +@admin.register(Config)
А если админ тупой? Лучше 10 раз перестраховаться.

2022-04-25 16:08 UTC, PerchunPak commented on autodonate/models.py
> +            raise ConfigKeyDoesNotExist
Почему не просто `TypeError` или `ValueError`. Зачем юзеру импортить еще что то, пусть уже тогда хотя бы `Config.NotExist` будет.

2022-04-26 18:12 UTC, PerchunPak commented on autodonate/models.py
> +    def set(cls, key: str, value: Any) -> None:  # type: ignore
Есть вариант сделать это в виде
```py
from typing import TypeVar


T = TypeVar("T")


def get(value, cast: T = str) -> T:
    ...
    return cast(value)
```

2022-04-26 20:08 UTC, PerchunPak commented on autodonate/admin.py
> +@admin.register(Config)
Вернул изменение в 453256f32178bc54a3233093d681dfcb3ab216cc.

2022-04-26 20:09 UTC, PerchunPak commented on autodonate/models.py
> +            raise ConfigKeyDoesNotExist
Изменил в https://github.com/fire-square/autodonate/pull/77/commits/220ed13c37357743653dcad8df7e6edcabb4d6b1.

2022-04-26 20:10 UTC, PerchunPak commented on autodonate/models.py
> +    def set(cls, key: str, value: Any) -> None:  # type: ignore
В таком случае `T` not-callable, как бы я его не крутил, лучше пусть останется `ubjson`.

2022-04-27 06:41 UTC, cofob commented on autodonate/models.py
> +    def set(cls, key: str, value: Any) -> None:  # type: ignore
> В таком случае `T` not-callable, как бы я его не крутил, лучше пусть останется `ubjson`.

Я ведь говорил что херня идея)

2022-04-27 06:43 UTC, merged