Добавил index приложение и static тэг
fire-square/autodonate pull request #79
Opened 2022-04-23 03:18 UTC by cofob

2022-04-23 03:20 UTC, cofob commented on index/views.py
> +    return render(request, "base.html")
Это выглядит вот так
![](https://lshort.deta.dev/n2xb6)

2022-04-23 07:34 UTC, PerchunPak requested changes
Не все посмотрел потому что PR требует значительных изменений.

2022-04-23 07:34 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +    """Copied from Django."""
Полностью? Зачем его копировать? Почему просто mock через наследование нельзя сделать?

2022-04-23 07:34 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        """Class method to parse prefix node and return a Node."""
Почему ты нигде не добавил докстринги про аргументы и то что метод возвращает?

2022-04-23 07:34 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        """Class method to parse prefix node and return a Node."""
И где типы?

2022-04-23 07:34 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +    Examples::
Почему два двоеточия?

2022-04-23 07:34 UTC, PerchunPak commented on tests/test_static.py
> +    print(static("test/file"))
print? Как минимум есть structlog

2022-04-23 09:47 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +        """Class method to parse prefix node and return a Node."""
Я полностью копировал и докстринги и код с джанга-исходников. Претензии направляй им.

2022-04-23 09:47 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +    Examples::
Потому что исходники джанга такие.

2022-04-23 09:48 UTC, cofob commented on tests/test_static.py
> +    print(static("test/file"))
а, забыл убрать дебаг код

2022-04-23 09:49 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +    """Copied from Django."""
Что такое `mock`? Ну и можно было сделать через наследование, да, что-то я сразу не подумал об этом.

2022-04-24 17:49 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +    """Copied from Django."""
В `pytest` это еще называется monkeypatch.

2022-04-24 17:50 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        """Class method to parse prefix node and return a Node."""
Так к тебе претензии раз ты тупо скопипастил вместо наследования.

2022-04-25 11:27 UTC, cofob commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить index приложение и static тэг](https://trello.com/c/JXFfEXXG/3-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-index-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8-static-%D1%82%D1%8D%D0%B3)

2022-04-25 16:35 UTC, PerchunPak requested changes

2022-04-25 16:35 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        """Copied from Django."""
Пожалуйста, нормальные док-строки.

2022-04-25 16:35 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +
Где типы?

2022-04-25 16:35 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        """Add ver arg to given url."""
Где описание аргумента и Returning секция?

2022-04-25 16:35 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +    """Join the given path with the STATIC_URL setting. For internal Django usage."""
Не буду увеличивать количество комментариев, но добавь **везде** типы и док-строки.

2022-04-25 16:35 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        /static/path/to/asset.css?ver=543564
Такое лучше перенести под имя и сделать в одну строку.

```py
"""Bla-bla.

Example ``/static/path/to/asset.css?ver=543564``.
....
"""
```

2022-04-25 16:35 UTC, PerchunPak commented on autodonate/settings.py
> +    "autodonate.lib",
Пусть наши сервисы будут в конце списка.

2022-04-25 16:35 UTC, PerchunPak commented on index/migrations/__init__.py
> +"""Stub."""
Что еще за stub? Напиши `Package for app migrations.` например.

2022-04-25 16:35 UTC, PerchunPak commented on index/migrations/__init__.py
> +"""Stub."""
И почему пустое? Плюс ты говорил удалить миграции чтобы сразу их в мастере добавить.

2022-04-25 18:50 UTC, PerchunPak requested changes

2022-04-25 20:02 UTC, PerchunPak commented on tests/test_static.py
> -def test_static() -> None:
А при чем тут `pytest-django`?

2022-04-26 04:30 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +
Типы не проставлены, потому что я не знаю какие тут типы. Это Django исходники. Попробую поискать.

2022-04-26 04:34 UTC, cofob commented on autodonate/settings.py
> +    "autodonate.lib",
А они не в конце?

2022-04-26 04:36 UTC, cofob commented on index/__init__.py
> +"""Index app."""
Так делает Django. Так буду делать я. Это удобнее.

2022-04-26 04:36 UTC, cofob commented on tests/test_static.py
> -def test_static() -> None:
То что тесты проваливаются без корректной настройки `Django`, которую делает `pytest-django`.

2022-04-26 04:37 UTC, cofob commented on index/migrations/__init__.py
> +"""Stub."""
Поправил. Миграции я не отправлял, но заранее сделал модуль под них.

2022-04-26 04:38 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +        /static/path/to/asset.css?ver=543564
Сделал.

2022-04-26 04:38 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +        """Add ver arg to given url."""
Добавил.

2022-04-26 04:48 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +
Проставил

2022-04-26 04:48 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +        """Copied from Django."""
Сделал

2022-04-26 07:12 UTC, PerchunPak commented on autodonate/settings.py
> +    "autodonate.lib",
Извини, я не увидел что `index` тоже мы.

2022-04-26 07:13 UTC, PerchunPak commented on tests/test_static.py
> -def test_static() -> None:
Я добавил сюда `pytest-django` в 42a34d356eed780ba97d6cdb8182bffda10cf415.

2022-04-26 07:50 UTC, PerchunPak requested changes

2022-04-26 07:50 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        Example: ``https://some.domain/static/path/to/asset.css?ver=543564``
Доки не смогут прочитать это. Нужно писать в формате:
```py
"""Short description.

Long description.

Args:
    something: Description.

Returns:
    Something object.

Raises:
    TypeError: argument ``something`` not a int.
"""
```
Examples в этом случае Long Description, а `Args`, `Returns` и `Raises` это секции. `Examples` это не секция, так что доки при парсинге просто проигнорируют ее, или вообще выдадут ошибку/предупреждение.

2022-04-26 07:50 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        Example: ``https://some.domain/static/path/to/asset.css?ver=543564``
Кстати странно, `sphinx-napoleon` должен поддерживать секцию `Examples`.
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/#docstring-sections

2022-04-26 07:50 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +    """Join the given path with the STATIC_URL setting. For internal Django usage."""
Типы ты проставил, а док-строки?

2022-04-26 07:53 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        """Add ver arg to given url."""
Не везде.

2022-04-26 07:55 UTC, PerchunPak commented on index/__init__.py
> +"""Index app."""
Очень много всего прийдется изменить для поддержки такого стиля, тем не менее, похоже `wemake` поддерживают такой стиль в своем `django-template` так что нужно будет добавить поддержку.

2022-04-26 08:51 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +    """Join the given path with the STATIC_URL setting. For internal Django usage."""
Они не везде нужны.

2022-04-26 08:51 UTC, cofob commented on autodonate/lib/templatetags/statictags.py
> +        Example: ``https://some.domain/static/path/to/asset.css?ver=543564``
Доки - нет, а человек - да. Ты мне сам сказал написать в таком формате.

2022-04-26 11:33 UTC, merged

2022-04-26 12:00 UTC, PerchunPak commented on autodonate/lib/templatetags/statictags.py
> +        Example: ``https://some.domain/static/path/to/asset.css?ver=543564``
Я сказал в другом формате. В другом месте.